export class Formsclass {
    id:number;
    firstName:string='';
    lastName:string='';
    email:any;
    address:string='';
    dateOfBirth:any;
    city:any;
    country:any;
    rating:any;
    status:any;
    fatherName:string='';
    fatherOccupation:string='';
    fatherMobileNumber:string='';
    motherName:string='';
    motherOccupation:string='';
    mothermobileNumber:string='';
    homeAddress:string=''
}
